# no chatblock permission
# chatblock. disable is default permission which will also be used if this is empty string
permission: "chatblock.disable"

# error message
error-message: "Sorry, your message includes forbidden characters."

# list of unacceptable characters
char-list:
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - ☻
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - Ͱ
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - ᗠ
  - ᗡ
  - ᗢ
  - ऄ
  - ੲ
  - Ǡ
  - Ƞ
  - ᒐ
  - ᒑ
  - ᒒ
  - ᒓ
  - ਐ
  - Ɛ
  - Ġ
  - ġ
  - Ħ
  - Ę
  - Ĉ
  - Ĉ
  - ą
  - ċ
  - Ë
  - ƨ
  - Ī
  - Ĝ
  - ĝ
  - Ł
  - Ǆ
  - Ş
  - õ
  - ؀
  - ᧠
  - ᧩
  - ᧮
  - ᧵
  - ᧴
  - ᭡
  - ᭧
  - ᭼
  - ᭻
  - ᭨
  - ᭶
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 